DROP TABLE IF EXISTS CATEGORIA CASCADE;
CREATE TABLE CATEGORIA (
	ID INT PRIMARY KEY,
	NAME VARCHAR2 (4000)

);

DROP TABLE IF EXISTS PRODUCTO CASCADE;
CREATE TABLE PRODUCTO (
	ID INT,
	NAME VARCHAR2 (4000),
	PRICE FLOAT,
	CATEGORY_ID INT,
	PRIMARY KEY (ID),
	FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIA (ID)
);

DROP SEQUENCE hibernate_sequence;
CREATE SEQUENCE hibernate_sequence
 START WITH     1
 INCREMENT BY   1;